#!/bin/sh

# Run PMD on the files being committed
pmd -d src -R pmd/rules.xml

# Check the exit code of PMD
if [ $? -ne 0 ]; then
    # PMD found issues, so exit with a non-zero code to prevent the commit
    exit 1
fi
